name: dotnet-build

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '0 11 * * *'  # Executa todos os dias às 11h UTC

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checar o repositório
      uses: actions/checkout@v2  # Usando uma action pré-existente para fazer o checkout do código *
      
